### ISSUE TITLE
Add replacements for POSIX find

### ISSUE THREAD

**Issue by Celti** [Manishearth/oreutils#3]
[`fd`](https://github.com/sharkdp/fd) is a spectacular replacement for traditional POSIX find. [`fselect`](https://github.com/jhspetersson/fselect) is nowhere close to a direct replacement but is ultimately very powerful.

**Comment by Manishearth** [comment]
fd is already included https://github.com/Manishearth/oreutils/blob/master/src/main.rs#L61
