### ISSUE TITLE
Add homebrew support

### ISSUE THREAD

**Issue by ritesh** [Manishearth/oreutils#7]
It would be nice to have this installable via homebrew on macOS (and potentially other supported platforms). For folks who don’t have cargo installed but want cool CLI tools.

I don’t have any experience building homebrew packages but I’m happy to investigate if this is worth doing?

**Comment by Manishearth** [comment]
I think from the homebrew side you can just have a package that installs everything directly.

I'm not really interested in doing packaging right now, packaging can be annoying.

I'd also have to wait for this to get popular before doing so.
